### ISSUE TITLE
UI 刷新监控，如果 view 不在主线程刷新，你将会收到通知。

### ISSUE THREAD

**Issue by dadpp** [CUITCHE/PerformanceAnalyzer#1]
UI 卡顿监测这一块功能是怎么实现的呢,网上的都依赖
![image](https://cloud.githubusercontent.com/assets/8268339/17732001/7216522c-64a2-11e6-863f-ecb20fc56161.png)

**Comment by wzhejunqiu** [comment]
UI主线程检测，通过hook UIView的方法：setNeedsLayout,setNeedsDisplay,setNeedsDisplayInRect, layoutIfNeeded等刷新UI的方法，在方法里面判断当前是否处于主线程。在我的代码中有相应的实现哦。

后续还会增强UI主线程检测的强度，还请留意我的更新计划😀

**Comment by Rannie** [comment]
增强检测的强度是指？

**Comment by wzhejunqiu** [comment]
setNeedsLayout,setNeedsDisplay,setNeedsDisplayInRect, layoutIfNeeded这些方法有可能无法全部覆盖UI刷新。

**Comment by dadpp** [comment]
如果可以把上面那里面的几句核心代码抽取出来就搞定了,不用依赖他的第三方库了
