### ISSUE TITLE
请教下改如何运行起来呢？

### ISSUE THREAD

**Issue by oatsuper** [CUITCHE/PerformanceAnalyzer#2]
1.  这个工程中没有startPerformanceAnalyzer 函数的具体实现呀
2. CUICHE 项目中， startPerformanceAnalyzer 函数也是空的
   我该如何使用呢？

**Comment by wzhejunqiu** [comment]
有两种方式启动：
- 将PerformanceAnalyzer/CHPerformanceAnalyzer/CHPerformanceAnalyzer/PerformanceAnalyzer/拷贝至你的工程编译运行即可。
  
  > 请阅读我的[README.md](https://github.com/CUITCHE/PerformanceAnalyzer/blob/master/README.CN.md)
- 包含我的静态库，在main.mm文件中包含CHPerformanceAnalyzer.h文件，在main函数中调用startPerformanceAnalyzer()方法。
  
  > 请阅读我的静态库使用说明，[Support Static Library](https://github.com/CUITCHE/PerformanceAnalyzer/tree/master/CHPerformanceAnalyzer/PerformanceAnalyzer)

对于第二个问题，uhm...`startPerformanceAnalyzer`函数，是用来打开静态库，使PerformanceAnalyzer的符号加载到你的工程。`startPerformanceAnalyzer`不做任何事情，仅仅在静态库启动的时候用。

**Comment by oatsuper** [comment]
我编译运行webview 百度那个例子，已经可以正常运行，
但是集成到我自己的项目中，我使用方法一，CHPerformanceAnalyzer的相关代码都已经加入到了自己的工程中，但是编译完没有 浮层的现实，是和AppDelegate 相关么？
这个AppDelegate 可否给些明显的建议，我现在的项目中已经有个浮层控件做调试用了，您这个工程也是浮层现实，我该如何处理下？
谢谢哦

**Comment by wzhejunqiu** [comment]
多个浮层控件不影响。唯一影响的是，CHPerformanceAnalyzer会拦截手机shake事件。
如果您的AppDelegate不是`AppDelegate`，还请在文件`CHPerformancerExterns.m`最后一行的`NSString *CHPerformanceAnalyzerApplicationDelegateClassName = @"Your app delegate name";`修改自己的app delegate.

**Comment by oatsuper** [comment]
已经搞定，哈哈
